name: Release Obsidian Plugin

permissions:
  id-token: write
  contents: read
  attestations: write

on:
  push:
    tags:
    - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24.x'

    - name: Get Version
      id: version
      run: |
        echo "tag=$(git describe --abbrev=0 --tags)" >> $GITHUB_OUTPUT

    - name: Build
      id: build
      run: |
        npm ci
        npm run build --if-present

    - name: Generate artifact attestation
      uses: actions/attest@v4
      with:
        subject-path: |
           main.js
           manifest.json
           styles.css

    - name: Create Release and Upload Assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          main.js
          manifest.json
          styles.css
        name: ${{ steps.version.outputs.tag }}
        tag_name: ${{ steps.version.outputs.tag }}
        draft: true
